version: '3'
services:
  client:
    container_name: client
    build:
      context: ./client
      dockerfile: ./docker/Dockerfile
    volumes:
      - ./client:/app
    ports: 
      - 8080:8080
    networks: 
      - common
      
  server:
    container_name: server
    build:
      context: ./server
      dockerfile: ./docker/Dockerfile
    volumes:
      - ./server:/app
    ports: 
      - 4000:4000
    networks: 
      - common
    
networks: 
  common:
    driver: bridge